### ISSUE TITLE
Wallpapers turn black on my dual-monitors

### ISSUE THREAD

**Issue by kerhbal** [ianmartinez/AtlinUtils#1]
Wallpapers of two monitors are both black after using this.
Before:
![before](https://user-images.githubusercontent.com/11629684/46237882-62ade480-c355-11e8-9a54-c5b58347b6ca.png)
After:
![after](https://user-images.githubusercontent.com/11629684/46237885-66416b80-c355-11e8-8f1d-88c8febfff8b.png)

**Comment by ianmartinez** [comment]
![capture](https://user-images.githubusercontent.com/8404676/46239001-f1bbfc00-c357-11e8-9360-5df9f43f251b.JPG)
I'm honestly not sure what could be the source of this issue. It seems to be working on my two monitors.

**Comment by kerhbal** [comment]
Yeah, it's pretty weird
![2](https://user-images.githubusercontent.com/11629684/46239141-5714ea80-c362-11e8-86a8-9e7005d6c2b1.gif)

**Comment by ianmartinez** [comment]
Does is work if you unplug one of the monitors? Or if you run it as admin?

**Comment by kerhbal** [comment]
Run it as admin doesn't help. And I also find out that unplug doesn't help either... It happens when there is just one monitor.

**Comment by ianmartinez** [comment]
Can you download the latest 1.3 version? I added some logging to it. It will create a chameleon.log file in the same directory after it closes. Can copy that file over?

**Comment by duffett** [comment]
just making sure...did you download the wallpaper pack?
https://minhaskamal.github.io/DownGit/#/home?url=https:%2F%2Fgithub.com%2Fianmartinez%2FChameleon%2Ftree%2Fmaster%2FChameleon%2FWallpapers

**Comment by ianmartinez** [comment]
It looks like he did. The preview thumbnails wouldn't be populated otherwise.

**Comment by kerhbal** [comment]
I found the reason. Maybe it's some localization problem. My system language is Chinese.
Here is the log:

> [2018-09-28 23:22:09.616 Info] Changing wallpaper to "D:\Files\Saved\Sync\Portable\Chameleon-壁纸变化\Wallpapers\Time\11下午.jpg" for Time = 11下午
 [2018-09-28 23:22:09.616 Error] "D:\Files\Saved\Sync\Portable\Chameleon-壁纸变化\Wallpapers\Time\11下午.jpg" does not exist!

"11下午" Means 11 PM.

**Comment by kerhbal** [comment]
Example:
When pick up one image for 11PM, it copys the source file to its designated folder "time" and rename the file to "11PM" . However, when it calls the image for 11PM it uses my system language"11下午", which is not agree with the existing file name.

**Comment by ianmartinez** [comment]
The 1.4 update I just pushed should fix the time localization issue.

**Comment by kerhbal** [comment]
Yes, this time it works out under a small condition:
I also need to make sure the path contains only English or it won't work. 
Thank you!

**Comment by ianmartinez** [comment]
The 1.5 update I just released should fix that!

**Comment by kerhbal** [comment]
Yeah it's fixed.
Thank you!
