### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by shadowchild1234** [ianmartinez/AtlinUtils#14]
I think the program is slowing my computor down, but I cant check because I can't uninstall. the zip file came with no way to do it.

**Comment by ianmartinez** [comment]
The program's installer creates an uninstall entry so you can remove it in the Windows 10 settings app:
![image](https://user-images.githubusercontent.com/8404676/113029708-5c7d6680-9152-11eb-83ba-769867cf2131.png)

**Comment by shadowchild1234** [comment]
That works, Thank you!
