### ISSUE TITLE
Does this have a Cryptomining Malware?

### ISSUE THREAD

**Issue by KontrolG** [ianmartinez/AtlinUtils#16]
I recently install this application, but suddenly one day I started to see my GPU going to 100% use without doing anything. When I open the task manager it goes down to 0% inmediatly.

I made a scan in https://manalyzer.org/:

![image](https://user-images.githubusercontent.com/43476781/236625982-ee45814e-6fd0-494d-94fb-372fdd89ad77.png)

**Comment by ianmartinez** [comment]
No it does not. You can look through the source and compile it and it will produce exactly the same.
