### ISSUE TITLE
Auto Run Minimised

### ISSUE THREAD

**Issue by thomassmart** [ianmartinez/AtlinUtils#4]
Sorry if this is already documented (I did search for it I swear)

It would be good to auto launch the app minimised and run either through a .exe switch, or through a configuration in app.

Cheers!

**Comment by ianmartinez** [comment]
I added a new command line switch for this in the 1.8 release:
"Chameleon.exe -a"

To run on startup:
1) Go to %USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup  into the file explorer
2) Create a shortcut for "{path to your chameleon.exe} -a"
3) It should now run at startup
