### ISSUE TITLE
Error on every click

### ISSUE THREAD

**Issue by LuminarySage** [ianmartinez/AtlinUtils#5]
When I run the program, these two error messages show up:
![chameleon64_2019-01-02_18-31-25](https://user-images.githubusercontent.com/24306400/50617762-c435a000-0ebc-11e9-96e1-c2c249d346e0.png)
![chameleon64_2019-01-02_18-31-11](https://user-images.githubusercontent.com/24306400/50617764-c566cd00-0ebc-11e9-8ad5-32f9306b7d54.png)

Then, when I click on anything in the program (except the Settings and About buttons plus the Patreon link), this message shows up
![chameleon64_2019-01-02_18-31-04](https://user-images.githubusercontent.com/24306400/50617811-fba44c80-0ebc-11e9-8fa4-674a86f6c5fb.png)
Even trying to close it will show the same error message

**Comment by hochoch** [comment]
same here - glad i'm not the only one!

**Comment by sandsterboy** [comment]
I get the same "In 'stream'" error on launching.  If I continue past it, I cannot localize the weather settings as it shows no options under state or weather stations.  :(

**Comment by ianmartinez** [comment]
This was due to a change in the weather server. I've released a new version. Try it and see if it fixes your issue.

**Comment by LuminarySage** [comment]
Nope, nothing changed.

**Comment by LuminarySage** [comment]
Is it supposed to come with Settings.ini and chameleon.log or are those created on the first time you open the program?

**Comment by ianmartinez** [comment]
The files are generated at startup. I don't think your account has permissions to write to that area without elevating it to admin. Try putting the program somewhere else and it should work.

**Comment by LuminarySage** [comment]
Oh it works now, thanks! It was in the C drive before, maybe that's why

**Comment by LuminarySage** [comment]
I just wanted to mention that the In 'stream:' issue is also resolved in 1.7
