### ISSUE TITLE
[Feature Request] Run on startup

### ISSUE THREAD

**Issue by BobtheUltimateProgrammer** [ianmartinez/AtlinUtils#7]
Great app! Wonderful work. It would be nice if the program had an option to start when Windows boot up. 

The method I am using now is adding the app's shortcut to the Windows Startup folder but the problem is that the settings window shows up every startup and  I have to hit the "Run" button every time. It would be nice if the program had an option to startup without having to show the settings window. It like logging in to the current weather. Thanks and keep up the good work!

**Comment by ianmartinez** [comment]
I added a command line flag in the new 1.8 release that you can use to auto start it, like this:
"Chameleon.exe -a"

**Comment by BobtheUltimateProgrammer** [comment]
Thanks. Nice update. I got it working now.

It would be nice though, I know I’m picky, but if the settings windows doesn’t show at all. At each startup, Chameleon does run automatically and changes my wallpaper but the settings window is minimized.
